﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using Refit;
using System.Text;
using System.Threading.Tasks;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace LifxHttp
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedILifxApi : ILifxApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedILifxApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<Light> GetLight(string auth,string selector)
        {
            var arguments = new object[] { auth,selector };
            return (Task<Light>) methodImpls["GetLight"](Client, arguments);
        }

        public virtual Task<List<Light>> ListLights(string auth,string selector)
        {
            var arguments = new object[] { auth,selector };
            return (Task<List<Light>>) methodImpls["ListLights"](Client, arguments);
        }

        public virtual Task<List<ApiResult>> TogglePower(string auth,string selector)
        {
            var arguments = new object[] { auth,selector };
            return (Task<List<ApiResult>>) methodImpls["TogglePower"](Client, arguments);
        }

        public virtual Task<ApiResult> TogglePowerSingle(string auth,string selector)
        {
            var arguments = new object[] { auth,selector };
            return (Task<ApiResult>) methodImpls["TogglePowerSingle"](Client, arguments);
        }

        public virtual Task<List<ApiResult>> SetPower(string auth,string selector,string args)
        {
            var arguments = new object[] { auth,selector,args };
            return (Task<List<ApiResult>>) methodImpls["SetPower"](Client, arguments);
        }

        public virtual Task<ApiResult> SetPowerSingle(string auth,string selector,string args)
        {
            var arguments = new object[] { auth,selector,args };
            return (Task<ApiResult>) methodImpls["SetPowerSingle"](Client, arguments);
        }

        public virtual Task<List<ApiResult>> SetColor(string auth,string selector,string args)
        {
            var arguments = new object[] { auth,selector,args };
            return (Task<List<ApiResult>>) methodImpls["SetColor"](Client, arguments);
        }

        public virtual Task<ApiResult> SetColorSingle(string auth,string selector,string args)
        {
            var arguments = new object[] { auth,selector,args };
            return (Task<ApiResult>) methodImpls["SetColorSingle"](Client, arguments);
        }

    }
}


